[versions]
arrow = "2.0.1"
agp = "8.9.1"
androidx-activityCompose = "1.10.1"
androidx-lifecycle = "2.9.0-alpha06"
androidx-navigation = "2.9.0-alpha16"
androidx-uiTest = "1.7.8"
buildconfig = "5.6.2"
coil = "3.1.0"
compose = "1.8.0-beta02"
datastore = "1.1.4"
desugaring = "2.1.5"
detekt = "1.23.8"
detekt-compose = "0.4.22"
detekt-compose2 = "1.4.0"
hotReload = "1.0.0-alpha04"
kaml = "0.76.0"
kermit = "2.0.5"
koin = "4.1.0-Beta7"
kotest = "6.0.0.M3"
kotest-property-datetime = "2.0.0"
kotlin = "2.1.20"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.6.2"
kotlinx-serialization = "1.8.1"
kotlinpoet = "2.1.0"
ksp = "2.1.20-2.0.0"
ktor = "3.1.2"
materialkolor = "2.1.1"
mockk = "1.14.0"
mokkery = "2.7.2"
multiplatformSettings = "1.3.0"
navigation-material = "1.8.0-beta02"
room = "2.7.0"
sqlite = "2.5.0"
turbine = "1.2.0"
kotlinStdlib = "2.1.20"
kotlinTest = "2.1.20"
runner = "1.6.2"
core = "1.6.1"
junit = "1.2.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "hotReload" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }

[libraries]
# AndroidX
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }

# Arrow
arrow = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }

# Coil
coil = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

# Desugaring
desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }

# Detekt
detekt-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detekt-compose" }
detekt-compose2 = { module = "ru.kode:detekt-rules-compose", version.ref = "detekt-compose2" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# Datastore
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# Kaml
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }

# Kermit
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }

# Kotlin
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

# KotlinPoet
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Lifecycle
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

# Navigation
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
navigation-material = { module = "org.jetbrains.compose.material:material-navigation", version.ref = "navigation-material" }

# MaterialKolor
materialkolor = { module = "com.materialkolor:material-kolor", version.ref = "materialkolor" }

# Multiplatform Settings
multiplatformSettings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite"}

###
# Gradle
###
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradle-buildconfig = { module = "com.github.gmazzo.buildconfig:com.github.gmazzo.buildconfig.gradle.plugin", version.ref = "buildconfig" }
gradle-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }
gradle-compose-compiler = { module = "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin", version.ref = "kotlin" }
gradle-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradle-kotest = { module = "io.kotest:kotest-framework-multiplatform-plugin-gradle", version.ref = "kotest" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-ksp = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }
gradle-mokkery = { module = "dev.mokkery:mokkery-gradle", version.ref = "mokkery" }
gradle-room = { module = "androidx.room:room-gradle-plugin", version.ref = "room" }

###
# Test
###
androidx-uitest-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-uiTest" }
androidx-uitest-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-uiTest" }

# Kotest
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-property-datetime = { module = "io.kotest.extensions:kotest-property-datetime", version.ref = "kotest-property-datetime" }

# MockK
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

# Turbine
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTest" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }

[bundles]
# Deps for Core
core-common = [
    "arrow",
    "koin-core",
    "kotlinx-coroutines-core",
    "kotlinx-datetime",
    "kermit",
]
core-android = []
core-ios = []
core-desktop = []

core-common-ksp = []
core-android-ksp = []
core-ios-ksp = []
core-desktop-ksp = []

core-common-test = [
    "koin-test",
    "kotest-assertions-core",
    "kotest-engine",
    "kotest-property",
    "kotlinx-coroutines-test",
    "turbine",
]
core-android-test = [
    "kotest-junit5",
    "kotest-property-datetime",
    "mockk",
]
core-ios-test = [
    "kotest-property-datetime",
]
core-desktop-test = [
    "kotest-junit5",
    "kotest-property-datetime",
    "mockk",
]

core-common-test-ksp = []
core-android-test-ksp = []
core-ios-test-ksp = []
core-desktop-test-ksp = []

# Deps for Data Preferences
data-preferences-common = [
    "kotlinx-serialization-json",
    "androidx-datastore",
    "androidx-datastore-preferences",
    "room-runtime",
    "sqlite-bundled",
]
data-preferences-android = []
data-preferences-ios = []
data-preferences-desktop = []

data-preferences-common-ksp = [
    "room-compiler",
]
data-preferences-android-ksp = []
data-preferences-ios-ksp = []
data-preferences-desktop-ksp = []

data-preferences-common-test = []
data-preferences-android-test = []
data-preferences-ios-test = []
data-preferences-desktop-test = []

data-preferences-common-test-ksp = []
data-preferences-android-test-ksp = []
data-preferences-ios-test-ksp = []
data-preferences-desktop-test-ksp = []

# Deps for Data Remote
data-remote-common = [
    "ktor-client-core",
    "ktor-client-content-negotiation",
    "ktor-client-logging",
    "ktor-serialization-json"
]
data-remote-android = [
    "ktor-client-okhttp",
]
data-remote-ios = [
    "ktor-client-darwin",
]
data-remote-desktop = [
    "ktor-client-okhttp",
]

data-remote-common-ksp = []
data-remote-android-ksp = []
data-remote-ios-ksp = []
data-remote-desktop-ksp = []

data-remote-common-test = []
data-remote-android-test = []
data-remote-ios-test = []
data-remote-desktop-test = []

data-remote-common-test-ksp = []
data-remote-android-test-ksp = []
data-remote-ios-test-ksp = []
data-remote-desktop-test-ksp = []

# Deps for UI
ui-common = [
    "androidx-lifecycle-viewmodel",
    "androidx-lifecycle-runtime-compose",
    "androidx-navigation-compose",
    "coil",
    "koin-compose",
    "koin-compose-viewmodel",
    "koin-compose-viewmodel-navigation",
    "kotlinx-serialization-json",
    "navigation-material",
]
ui-android = []
ui-ios = []
ui-desktop = [
    "kotlinx-coroutines-swing",
]

ui-common-ksp = []
ui-android-ksp = []
ui-ios-ksp = []
ui-desktop-ksp = []

ui-common-test = []
ui-android-test = []
ui-ios-test = []
ui-desktop-test = []

ui-common-test-ksp = []
ui-android-test-ksp = []
ui-ios-test-ksp = []
ui-desktop-test-ksp = []

app-common = []
app-android = [
    "androidx-activity-compose",
    "coil",
]
app-ios = []
app-desktop = []

build-config = [
    "kaml",
    "kotlinpoet",
]

gradle = [
    "gradle-android",
    "gradle-buildconfig",
    "gradle-compose",
    "gradle-compose-compiler",
    "gradle-detekt",
    "gradle-kotest",
    "gradle-kotlin",
    "gradle-ksp",
    "gradle-mokkery",
    "gradle-room",
]
